### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="97565-101">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="97565-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="97565-102">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="97565-102">Design for security</span></span>
  description: <span data-ttu-id="97565-103">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="97565-103">Design for security</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1b55aacd394eb8f956c0b0ef45713cdcc57a03b0
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46361399"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="97565-104">Testa dina kunskaper</span><span class="sxs-lookup"><span data-stu-id="97565-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="97565-105">Vilka av följande typer av data kan behöva ha säkerhetsskydd?</span><span class="sxs-lookup"><span data-stu-id="97565-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="97565-106">Kundinformation som innehåller personuppgifter</span><span class="sxs-lookup"><span data-stu-id="97565-106">Customer data that contains personal information</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-107">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="97565-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="97565-108">Finansiella data som stöd för verksamheten</span><span class="sxs-lookup"><span data-stu-id="97565-108">Financial data supporting business operations</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-109">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="97565-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="97565-110">Immateriella rättigheter</span><span class="sxs-lookup"><span data-stu-id="97565-110">Intellectual property</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-111">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="97565-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="97565-112">Alla alternativ ovan kan behöva säkerhetsskydd</span><span class="sxs-lookup"><span data-stu-id="97565-112">All of the above may need security protections</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="97565-113">Alla alternativ ovan kan ha ytterligare säkerhetsskydd.</span><span class="sxs-lookup"><span data-stu-id="97565-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="97565-114">Vilket av följande är ett exempel på en attack du kan se på princip- och åtkomstnivå?</span><span class="sxs-lookup"><span data-stu-id="97565-114">Which of the following is an example of an attack you might see at the policies & access layer?</span></span>
    choices:
    - content: <span data-ttu-id="97565-115">Exponerade autentiseringsuppgifter som publicerats online</span><span class="sxs-lookup"><span data-stu-id="97565-115">Exposed credentials posted online</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="97565-116">Exponerade autentiseringsuppgifter är en enorm risk för en organisation och gäller på princip- och åtkomstnivå.</span><span class="sxs-lookup"><span data-stu-id="97565-116">Exposed credentials are a huge risk to an organization and apply at the policies & access layer.</span></span>
    - content: <span data-ttu-id="97565-117">En SYN flood-attack</span><span class="sxs-lookup"><span data-stu-id="97565-117">A SYN flood attack</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-118">SYN flood-attacker är en typ av DoS-attack som ofta sker i nätverksperimetern.</span><span class="sxs-lookup"><span data-stu-id="97565-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="97565-119">Följa efter en anställd in i ett datacenter utan at behöva ange autentiseringsuppgifter</span><span class="sxs-lookup"><span data-stu-id="97565-119">Following an employee into a datacenter without presenting credentials</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-120">Att följa efter en anställd in i ett datacenter är ett angrepp på fysisk nivå.</span><span class="sxs-lookup"><span data-stu-id="97565-120">Following an employee into a datacenter is a physical layer attack.</span></span>
    - content: <span data-ttu-id="97565-121">Utpressningstrojaner som krypterar diskarna för en virtuell dator</span><span class="sxs-lookup"><span data-stu-id="97565-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="97565-122">Utpressningstrojaner är en attack på VM-/beräkningsnivå.</span><span class="sxs-lookup"><span data-stu-id="97565-122">Ransomware attacks are a VM/compute layer attack.</span></span>
