### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="a54e5-101">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="a54e5-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="a54e5-102">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="a54e5-102">Design for security</span></span>
  description: <span data-ttu-id="a54e5-103">Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="a54e5-103">Design for security</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b1f1fd5afaa153340eee740bd0071fc8295c63e6
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44245723"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="a54e5-104">Kunskapskontroll – Design för säkerhet</span><span class="sxs-lookup"><span data-stu-id="a54e5-104">Knowledge check - Design for security</span></span>
  questions:
  - content: <span data-ttu-id="a54e5-105">Vilka av följande typer av data kan behöva ha säkerhetsskydd?</span><span class="sxs-lookup"><span data-stu-id="a54e5-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="a54e5-106">Kundinformation som innehåller personuppgifter</span><span class="sxs-lookup"><span data-stu-id="a54e5-106">Customer data that contains personal information</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-107">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="a54e5-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="a54e5-108">Finansiella data som stöd för verksamheten</span><span class="sxs-lookup"><span data-stu-id="a54e5-108">Financial data supporting business operations</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-109">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="a54e5-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="a54e5-110">Data som innehåller immateriell egendom</span><span class="sxs-lookup"><span data-stu-id="a54e5-110">Data containing intellectual property</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-111">Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.</span><span class="sxs-lookup"><span data-stu-id="a54e5-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="a54e5-112">Alla alternativ ovan kan behöva säkerhetsskydd</span><span class="sxs-lookup"><span data-stu-id="a54e5-112">All of the above may need security protections</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="a54e5-113">Alla alternativ ovan kan ha ytterligare säkerhetsskydd.</span><span class="sxs-lookup"><span data-stu-id="a54e5-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="a54e5-114">Vilket av följande är ett exempel på en attack du kan se på perimeternivå?</span><span class="sxs-lookup"><span data-stu-id="a54e5-114">Which of the following is an example of an attack you might see at the perimeter layer?</span></span>
    choices:
    - content: <span data-ttu-id="a54e5-115">Exponerade autentiseringsuppgifter som publicerats online</span><span class="sxs-lookup"><span data-stu-id="a54e5-115">Exposed credentials posted online</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-116">Exponerade autentiseringsuppgifter är en enorm risk för en organisation men är inte en perimeterattack.</span><span class="sxs-lookup"><span data-stu-id="a54e5-116">Exposed credentials are a huge risk to an organization, but are not a permiter attack.</span></span>
    - content: <span data-ttu-id="a54e5-117">En SYN flood-attack</span><span class="sxs-lookup"><span data-stu-id="a54e5-117">A SYN flood attack</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="a54e5-118">SYN flood-attacker är en typ av DoS-attack som ofta sker i nätverksperimetern.</span><span class="sxs-lookup"><span data-stu-id="a54e5-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="a54e5-119">Door drafting för att komma in i ett datacenter</span><span class="sxs-lookup"><span data-stu-id="a54e5-119">Door drafting to get into a datacenter</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-120">Door drafting är en attack på den fysiska nivån.</span><span class="sxs-lookup"><span data-stu-id="a54e5-120">Door drafting is a physical layer attack.</span></span>
    - content: <span data-ttu-id="a54e5-121">Utpressningstrojaner som krypterar diskarna för en virtuell dator</span><span class="sxs-lookup"><span data-stu-id="a54e5-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="a54e5-122">Utpressningstrojaner är en attack på VM-/beräkningsnivå.</span><span class="sxs-lookup"><span data-stu-id="a54e5-122">Ransomware attacks are a VM/compute layer attack.</span></span>
