### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: Distributionsmodeller för molnet
metadata:
  title: Distributionsmodeller för molnet
  description: Distributionsmodeller för molnet
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/4-cloud-deployment-models.md)]