### YamlMime:ModuleUnit
uid: principles-cloud-computing.4-cloud-deployment-models
title: <span data-ttu-id="86e29-101">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="86e29-101">Cloud deployment models</span></span>
metadata:
  title: <span data-ttu-id="86e29-102">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="86e29-102">Cloud deployment models</span></span>
  description: <span data-ttu-id="86e29-103">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="86e29-103">Cloud deployment models</span></span>
  ms.openlocfilehash: 351e3768c891f23e2f510b4142b36b2695f8207a
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43414598"
durationInMinutes: 10
content: '[!include[](includes/4-cloud-deployment-models.md)]'
