### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: Arbeta med – skapa en skalningsuppsättning och konfigurera automatisk skalning
metadata:
  title: Arbeta med – skapa en skalningsuppsättning och konfigurera automatisk skalning
  description: Arbeta med – skapa en skalningsuppsättning och konfigurera automatisk skalning
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]