### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="4d6fa-101">Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb</span><span class="sxs-lookup"><span data-stu-id="4d6fa-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="4d6fa-102">Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb</span><span class="sxs-lookup"><span data-stu-id="4d6fa-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="4d6fa-103">Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb</span><span class="sxs-lookup"><span data-stu-id="4d6fa-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 94af9097bf2ee37e91e93d2e51d1d5cc79eb874d
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46358703"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
