### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Konfigurera appar att skicka eller ta emot meddelanden via en händelsehubb
metadata:
  title: Konfigurera appar att skicka eller ta emot meddelanden via en händelsehubb
  description: Konfigurera appar att skicka eller ta emot meddelanden via en händelsehubb
  ms.openlocfilehash: e52c36959360c571ac76dc9906aa6c26be2ab487
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43838587"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
