### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Övning – Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
metadata:
  title: Övning – Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  description: Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: de40d61e225340c649c9efec1ac10093508b9459
  ms.sourcegitcommit: bfff31db64f2c8831293efda430f58470b5e2617
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "45994783"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
