### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Övning – Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
metadata:
  title: Övning – Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  description: Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]