### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="da279-101">Övning – Aktivera och konfigurera diskcache för virtuella Azure-datorer med hjälp av Azure Portal</span><span class="sxs-lookup"><span data-stu-id="da279-101">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="da279-102">Övning – Aktivera och konfigurera diskcache för virtuella Azure-datorer med hjälp av Azure Portal</span><span class="sxs-lookup"><span data-stu-id="da279-102">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="da279-103">Övning – Aktivera och konfigurera diskcache för virtuella Azure-datorer med hjälp av Azure Portal</span><span class="sxs-lookup"><span data-stu-id="da279-103">Exercise - Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 85d7905334c09c828dea8329dcc00f3f72ffa6d3
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46357127"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]'
