### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Högerklicka på källdata - aktivera och konfigurera Azure VM-disk-cacheminne med hjälp av Azure portal
metadata:
  title: Högerklicka på källdata - aktivera och konfigurera Azure VM-disk-cacheminne med hjälp av Azure portal
  description: Högerklicka på källdata - aktivera och konfigurera Azure VM-disk-cacheminne med hjälp av Azure portal
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]