### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: <span data-ttu-id="cf47c-101">Hantera cacheinställningar med PowerShell</span><span class="sxs-lookup"><span data-stu-id="cf47c-101">Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="cf47c-102">Hantera cacheinställningar med PowerShell</span><span class="sxs-lookup"><span data-stu-id="cf47c-102">Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="cf47c-103">Hantera cacheinställningar med PowerShell</span><span class="sxs-lookup"><span data-stu-id="cf47c-103">Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b862288f8868319d3a3e0c681632987fbc6419ac
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45782086"
durationInMinutes: 5
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
