### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Skapa ett Azure IoT Central-program
metadata:
  title: Skapa ett Azure IoT Central-program
  description: Skapa ett Azure IoT Central-program
  ms.openlocfilehash: e8c698bdbf44cc17d687466702c06b59f7023806
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43796395"
durationInMinutes: 12
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
