### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="aeb64-101">Övning – Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="aeb64-101">Exercise - Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="aeb64-102">Övning – Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="aeb64-102">Exercise - Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="aeb64-103">Övning – Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="aeb64-103">Exercise - Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: 81492226750978399fb2a82fb32c14b5ddefb08d
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43228896"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
