### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: Lägga till Azure Storage-konfiguration i din app
metadata:
  title: Lägga till Azure Storage-konfiguration i din app
  description: Lägga till Azure Storage-konfiguration i din app
  ms.openlocfilehash: fe194feea9e7ecd5018060b7451b9fa0b8bfba1f
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792213"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
