### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="173e7-101">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="173e7-101">Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="173e7-102">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="173e7-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="173e7-103">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="173e7-103">Add Azure Storage configuration to your app</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: d6c6e6e4d919e77b644a73fe89304b4934f55058
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44248154"
interactive: bash-editor
durationInMinutes: 10
content: '[!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]'
