### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: Anslut till din Azure Storage-konfiguration
metadata:
  title: Anslut till din Azure Storage-konfiguration
  description: Anslut till din Azure Storage-konfiguration
  ms.openlocfilehash: d7b2a71726a5830927bb64e8d4008c9f9df291f4
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792757"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
