### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="5641a-101">Övning – Ansluta till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="5641a-101">Exercise - Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="5641a-102">Övning – Ansluta till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="5641a-102">Exercise - Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="5641a-103">Övning – Ansluta till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="5641a-103">Exercise - Connect with your Azure Storage configuration</span></span>
  ms.openlocfilehash: d712e34b220d3ebb9847cb907fb512fb4de7da0b
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43228474"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
