### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="ca653-101">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="ca653-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="ca653-102">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="ca653-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="ca653-103">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="ca653-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 12d10497be5490db01c1822d11cd81f3145588f5
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43179955"
durationInMinutes: 12
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
