### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: Konfigurera en lokal miljö för containerutveckling
  description: Konfigurera en lokal miljö för containerutveckling.
  ms.openlocfilehash: f33047eb1295ea2dd44904a8e2ddb1d78b413682
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727911"
title: Konfigurera en lokal miljö för containerutveckling
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
