### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: Konfigurera en lokal miljö för containerutveckling
  description: Konfigurera en lokal miljö för containerutveckling.
  displayType: one-column
  ms.openlocfilehash: 943d4a5d8cb84c7b07d1e8ae49dac8636763f797
  ms.sourcegitcommit: 16445658b8c25e5f5cbcfc7b1d8a36222f4e902c
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42906908"
title: Konfigurera en lokal miljö för containerutveckling
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
