### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Konfigurera Redis Cache
metadata:
  title: Konfigurera Redis Cache
  description: Konfigurera Redis Cache
  ms.openlocfilehash: 15a6f66099ae01020efc34612c3e04610217830f
  ms.sourcegitcommit: 92580185df76595daa4cf68a5311019c85fe7bf3
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42874057"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
