### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: Skydda ditt nätverk
metadata:
  title: Skydda ditt nätverk
  description: I den här kursdelen ska vi titta närmare på hur du skyddar din nätverksinfrastruktur.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 434584c1861f5b8031069c787b878c654a8ba848
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46360351"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
