### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: <span data-ttu-id="35a86-101">Skydda ditt nätverk</span><span class="sxs-lookup"><span data-stu-id="35a86-101">Protect your network</span></span>
metadata:
  title: <span data-ttu-id="35a86-102">Skydda ditt nätverk</span><span class="sxs-lookup"><span data-stu-id="35a86-102">Protect your network</span></span>
  description: <span data-ttu-id="35a86-103">I den här kursdelen ska vi titta närmare på hur du skyddar din nätverksinfrastruktur</span><span class="sxs-lookup"><span data-stu-id="35a86-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9e292fa70474a3250e8b53689a2bedaaf261ea96
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246131"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
