### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="61de8-101">Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="61de8-101">Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="61de8-102">Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="61de8-102">Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="61de8-103">Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="61de8-103">Create an ASP.NET Core application on Linux</span></span>
  ms.openlocfilehash: 739459c05bc62da00767173f7407e68ee0ae245c
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43414973"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
