### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: Skapa ett ASP.NET Core-program på Linux
metadata:
  title: Skapa ett ASP.NET Core-program på Linux
  description: Skapa ett ASP.NET Core-program på Linux
  ms.openlocfilehash: 739459c05bc62da00767173f7407e68ee0ae245c
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43414973"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
