### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="a3210-101">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="a3210-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="a3210-102">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="a3210-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="a3210-103">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="a3210-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: a8497a897faccb27bfeaf5812a5887ac15f97625
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42822472"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
