### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Konfigurera DSVM
metadata:
  title: Konfigurera Data Science Virtual Machine för djupinlärning
  description: Konfigurera Data Science Virtual Machine för djupinlärning
  ms.openlocfilehash: 54f188e18c055a9d80f3a71bf482a781b723b1e2
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43837158"
interactive: bash
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
