### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Ange miljövariabler
  description: Ange miljövariabler i Azure Container Instances.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Ange miljövariabler
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]