### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Nätverkssäkerhet
metadata:
  title: Nätverkssäkerhet
  description: I den här delen ska vi titta närmare på hur du kan skydda din nätverksinfrastruktur
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 90be1e461ce19e0bd7a18e869397db2d0ab3abfa
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240765"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: Kunskapskontroll – Nätverkssäkerhet
  questions:
  - content: Azure NSG:er kan användas för att skydda kommunikationen mellan vilka av följande?
    choices:
    - content: Kommunikation mellan virtuella datorer och Internet
      isCorrect: false
      incorrectExplanation: NSG:er kan användas för att skydda det här kommunikationsflödet, men detta är inte det enda rätta alternativet.
    - content: Kommunikation mellan virtuella datorer i ett virtuellt nätverk
      isCorrect: false
      incorrectExplanation: NSG:er kan användas för att skydda det här kommunikationsflödet, men detta är inte det enda rätta alternativet.
    - content: Kommunikation med system i ett lokalt nätverk
      isCorrect: false
      incorrectExplanation: NSG:er kan användas för att skydda det här kommunikationsflödet, men detta är inte det enda rätta alternativet.
    - content: Alla alternativ ovan
      isCorrect: true
      correctExplanation: NSG:er kan användas för att skydda alla ovanstående kommunikationsflöden.
  - content: Vilken av följande är inte en metod för att skydda Internetanslutna tjänster mot nätverksattacker?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: 'Azure DDoS kan användas för att skydda Internetanslutna tjänster mot en DoS-attack. '
    - content: Azure Application Gateway WAF
      isCorrect: false
      incorrectExplanation: Application Gateway WAF kan användas för att skydda Internetanslutna tjänster mot attacker, som till exempel XSS- och SQL-inmatning.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Azure Disk Encryption skyddar den virtuella datorns virtuella hårddiskar från exponering, men ger inget skydd mot nätverksbaserade attacker.
    - content: En virtuell nätverksinstallation
      isCorrect: false
      incorrectExplanation: Virtuella nätverksinstallationer kan ange anpassat nätverksskydd för dina Internetanslutna resurser.
