### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: <span data-ttu-id="073a4-101">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="073a4-101">Connect your simulated coffee machine to the application</span></span>
metadata:
  title: <span data-ttu-id="073a4-102">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="073a4-102">Connect your simulated coffee machine to the application</span></span>
  description: <span data-ttu-id="073a4-103">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="073a4-103">Connect your simulated coffee machine to the application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5e1c175df222a53ef2cd352fbd12feceabe25fad
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45764372"
durationInMinutes: 5
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
