### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="63f5e-101">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="63f5e-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="63f5e-102">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="63f5e-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="63f5e-103">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="63f5e-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5a6343fe6bbbe47ec15d343ce3e448315a27f606
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45773959"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
