### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.4-configure-a-load-balancer-in-azure
title: <span data-ttu-id="a1e4e-101">Konfigurera en lastbalanserare i Azure</span><span class="sxs-lookup"><span data-stu-id="a1e4e-101">Configure a Load Balancer in Azure</span></span>
metadata:
  title: <span data-ttu-id="a1e4e-102">Konfigurera en lastbalanserare i Azure</span><span class="sxs-lookup"><span data-stu-id="a1e4e-102">Configure a Load Balancer in Azure</span></span>
  description: <span data-ttu-id="a1e4e-103">Konfigurera en lastbalanserare i Azure</span><span class="sxs-lookup"><span data-stu-id="a1e4e-103">Configure a Load Balancer in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d215de8466824dfb203b3472207a44b5d1364828
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44238209"
durationInMinutes: 5
content: '[!include[](includes/4-configure-a-load-balancer-in-azure.md)]'
