### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-exercise-configure-a-load-balancer-in-azure
title: Arbeta med – Konfigurera en belastningsutjämnare i Azure
metadata:
  title: Arbeta med – Konfigurera en belastningsutjämnare i Azure
  description: Arbeta med – Konfigurera en belastningsutjämnare i Azure
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 20
content: |
  [!include[](includes/5-exercise-configure-a-load-balancer-in-azure.md)]