### YamlMime:ModuleUnit
uid: learn.secure-your-azure-sql-database.4-application-level-security
metadata:
  title: Säkerhet på radnivå
  description: Lär dig tekniker för att skydda känslig information och lär dig att undvika vid skrivning till programkod som har åtkomst till din databas.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Säkerhet på radnivå
durationInMinutes: 15
content: |
  [!include[](includes/4-application-level-security.md)]