### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: Övning – Skapa ett ASP.NET Core-program på Linux
metadata:
  title: Övning – Skapa ett ASP.NET Core-program på Linux
  description: Övning – Skapa ett ASP.NET Core-program på Linux
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43837195"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
