### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Identifiera flaskhalsar i appars prestanda
metadata:
  title: Identifiera flaskhalsar i appars prestanda
  description: I den här utbildningsenheten går vi igenom hur du kan identifiera flaskhalsar i appars prestanda
  ms.openlocfilehash: 0b5ab3a983a4b3dfc3a76c914b6a565f3ee7ed2c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43180657"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: Kunskapskontroll – Identifiera flaskhalsar i appars prestanda
  questions:
  - content: Vilket av följande alternativ beskriver bäst Application Insights?
    choices:
    - content: En enda fönsterruta för alla våra övervakningsbehov i Azure
      isCorrect: false
    - content: En implementering av mönstret Health Endpoint Monitoring (slutpunktsövervakning av tillstånd)
      isCorrect: false
    - content: En arbetsyta där du kan samla loggar från olika appar och delar av infrastrukturen
      isCorrect: false
    - content: En tjänst för att övervaka webbappars tillgänglighet, prestanda och användning
      isCorrect: true
  - content: Du kan använda Log Analytics till att spåra anpassade loggar och mått.
    choices:
    - content: Sant
      isCorrect: true
    - content: Falskt
      isCorrect: false
