### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Nätverkssäkerhet
metadata:
  title: Nätverkssäkerhet
  description: I den här delen ska vi titta närmare på hur du kan skydda din nätverksinfrastruktur
  ms.openlocfilehash: f98e9f24b46119fda8be58fb4a06f8f15d60ed66
  ms.sourcegitcommit: 1663afb13d55c1fce5f2dc4c0f78ef2d74902c33
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/31/2018
  ms.locfileid: "43366834"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: Kunskapstest – nätverkssäkerhet
  questions:
  - content: När du kör webbprogram i Azure App Service är ditt program helt skyddat och du behöver inte lägga till ytterligare säkerhetsskydd.
    choices:
    - content: Sant
      isCorrect: false
    - content: Falskt
      isCorrect: true
  - content: Vad av följande är inte en metod för att skydda Internetanslutna tjänster mot nätverksattacker?
    choices:
    - content: Azure DDoS
      isCorrect: false
    - content: Azure Application Gateway WAF
      isCorrect: false
    - content: Azure Disk Encryption
      isCorrect: true
    - content: En virtuell nätverksinstallation
      isCorrect: false
