### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="bb310-101">Nätverkssäkerhet</span><span class="sxs-lookup"><span data-stu-id="bb310-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="bb310-102">Nätverkssäkerhet</span><span class="sxs-lookup"><span data-stu-id="bb310-102">Network security</span></span>
  description: <span data-ttu-id="bb310-103">I den här delen ska vi titta närmare på hur du kan skydda din nätverksinfrastruktur</span><span class="sxs-lookup"><span data-stu-id="bb310-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.openlocfilehash: f98e9f24b46119fda8be58fb4a06f8f15d60ed66
  ms.sourcegitcommit: 1663afb13d55c1fce5f2dc4c0f78ef2d74902c33
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/31/2018
  ms.locfileid: "43366834"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="bb310-104">Kunskapstest – nätverkssäkerhet</span><span class="sxs-lookup"><span data-stu-id="bb310-104">Knowledge Check - Network security</span></span>
  questions:
  - content: <span data-ttu-id="bb310-105">När du kör webbprogram i Azure App Service är ditt program helt skyddat och du behöver inte lägga till ytterligare säkerhetsskydd.</span><span class="sxs-lookup"><span data-stu-id="bb310-105">When running web applications on Azure App Service, your application is fully secure and you do not need to provide additional security protections.</span></span>
    choices:
    - content: <span data-ttu-id="bb310-106">Sant</span><span class="sxs-lookup"><span data-stu-id="bb310-106">True</span></span>
      isCorrect: false
    - content: <span data-ttu-id="bb310-107">Falskt</span><span class="sxs-lookup"><span data-stu-id="bb310-107">False</span></span>
      isCorrect: true
  - content: <span data-ttu-id="bb310-108">Vad av följande är inte en metod för att skydda Internetanslutna tjänster mot nätverksattacker?</span><span class="sxs-lookup"><span data-stu-id="bb310-108">Which of the following is not a method of protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="bb310-109">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="bb310-109">Azure DDoS</span></span>
      isCorrect: false
    - content: <span data-ttu-id="bb310-110">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="bb310-110">Azure Application Gateway WAF</span></span>
      isCorrect: false
    - content: <span data-ttu-id="bb310-111">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="bb310-111">Azure Disk Encryption</span></span>
      isCorrect: true
    - content: <span data-ttu-id="bb310-112">En virtuell nätverksinstallation</span><span class="sxs-lookup"><span data-stu-id="bb310-112">A network virtual appliance</span></span>
      isCorrect: false
